stages:
- build
- test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: alpine:3.18
  before_script:
  - apk --no-cache add cmake clang clang-dev make gcc g++ libc-dev linux-headers make
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B ./Build/Release
  script:
  - cmake --build ./Build/Release --config Release --target all
  artifacts:
    paths:
    - ./Build/Release
    expire_in: 1 day
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull-push

ctest:
  stage: test
  image: alpine:3.18
  before_script:
  - apk --no-cache add cmake clang clang-dev make gcc g++ libc-dev linux-headers make
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B ./Build/Release
  script:
  - cd Build/Release
  - ctest --output-on-failure
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull

cppcheck:
  stage: test
  image: alpine:3.18
  before_script:
  - apk --no-cache add cmake clang clang-dev make gcc g++ libc-dev linux-headers make
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B ./Build/Release
  script:
  - cmake --build ./Build/Release --config Release --target CppCheck
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull

clang format:
  stage: test
  image: alpine:3.18
  before_script:
  - apk --no-cache add cmake clang clang-dev make gcc g++ libc-dev linux-headers make
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B ./Build/Release
  script:
  - cmake --build ./Build/Release --config Release --target ClangFormatDryRun
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull

clang check:
  stage: test
  image: alpine:3.18
  before_script:
  - apk --no-cache add cmake clang clang-dev make gcc g++ libc-dev linux-headers make
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B ./Build/Release
  script:
  - cmake --build ./Build/Release --config Release --target ClangCheckDryRun
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull
