stages:
- build
- test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: archlinux:latest
  before_script:
  - pacman -Sy --noconfirm base cmake ninja zip unzip curl tar clang glibc git pkg-config cppcheck
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -S . -B ./Build/Release -G Ninja
  script:
  - cmake --build ./Build/Release --config Release --target all
  artifacts:
    paths:
    - ./Binaries/Release
    expire_in: 1 day
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull-push

ctest:
  stage: test
  image: archlinux:latest
  before_script:
  - pacman -Sy --noconfirm base cmake ninja zip unzip curl tar clang glibc git pkg-config cppcheck
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -S . -B ./Build/Release -G Ninja
  script:
  - cd Build/Release
  - ctest --output-on-failure
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull

cppcheck:
  stage: test
  image: archlinux:latest
  before_script:
  - pacman -Sy --noconfirm base cmake ninja zip unzip curl tar clang glibc git pkg-config cppcheck
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -S . -B ./Build/Release -G Ninja
  script:
  - cmake --build ./Build/Release --config Release --target CppCheck
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull

clang format:
  stage: test
  image: archlinux:latest
  before_script:
  - pacman -Sy --noconfirm base cmake ninja zip unzip curl tar clang glibc git pkg-config cppcheck
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -S . -B ./Build/Release -G Ninja
  script:
  - cmake --build ./Build/Release --config Release --target ClangFormatDryRun
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull

clang check:
  stage: test
  image: archlinux:latest
  before_script:
  - pacman -Sy --noconfirm base cmake ninja zip unzip curl tar clang glibc git pkg-config cppcheck
  - cmake -DCMAKE_TOOLCHAIN_FILE=./Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -S . -B ./Build/Release -G Ninja
  script:
  - cmake --build ./Build/Release --config Release --target ClangCheckDryRun
  cache:
    paths:
    - ./Build/Release
    - ./Tools/vcpkg/packages
    policy: pull
