Build:
  stage: build
  image: $CI_REGISTRY_IMAGE/ci-build:latest
  before_script:
  - cmake --preset Test
  script:
  - cmake --build --preset Test
  cache:
    key: build-cache
    paths:
    - ./Binaries/
    - ./Build/
    - ./Tools/vcpkg/packages
    policy: pull-push
